services:
  frontend:
    build: .
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build:
      context: ../DRFProject/JournalApp
      dockerfile: Dockerfile
    container_name: drf-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ../DRFProject/JournalApp/.env
    volumes:
      - ../DRFProject/JournalApp:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      llm_service:
        condition: service_started

  celery:
    build:
      context: ../DRFProject/JournalApp
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A JournalApp worker -l info
    env_file:
      - ../DRFProject/JournalApp/.env
    volumes:
      - ../DRFProject/JournalApp:/app
    depends_on:
      - backend
      - redis
      - llm_service

  llm_service:
    build:
      context: ../DRFProject/llm_service
      dockerfile: Dockerfile
    container_name: llm_service
    ports:
      - "8001:8001"
    environment:
      - MODEL_PATH=/app/llm_models/Phi-3-mini-4k-instruct-q4.gguf
    volumes:
      - ../DRFProject/llm_service:/app
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-broker
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5433:5432"
    env_file:
      - ../DRFProject/JournalApp/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U me -d journalappdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    command: http --domain=velar-enzymatically-madlyn.ngrok-free.app backend:8000
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  postgres_data:
